
# File: config.yaml
# Author: Luke Burks
# Date: May 2018
# 
# Holds configuration values for interface.py and problemModel.py
#


###Data Collection
Interface:
  #Quality of Push Observations, {"NO","MEH","GOOD"}
  #NO: No push observations
  #MEH: Not super helpful
  #GOOD: On point, exact
  pushing: "NO"

  #Control Input Source, {"Human","MAP","POMCP"}
  #Human: Requires manual input with arrow keys
  #MAP: Takes shortest route to point of highest belief
  #POMCP: Calls JuliaPOMCP
  controlType: "MAP"

  #Number of points to retain in polygon fitting, {3-\inf}
  numSketchPoints: 4


  ###Drone Params

  #Seconds before drone is available to use again, {1-\inf}
  droneWaitTime: 5

  #Pixel radius of area revealed by drone sweep, {1-\inf}
  droneViewRadius: 75

  #How often, in Hz, the front end requests a control action, {0.00001-\inf}
  controlFreq: 3


###Model Params
Model:
  copInitPose: [200,500]
  targetInitPose: [400,200]

  #Random Beliefs, if belType is None, {1-40}
  numRandBel: 15

  #How far in each direction the robot clears fog, also determines
  #catch radius, {1-\inf}
  robotViewRadius: 25

  #How far the robots icon extends in each direction, in pixels, {1-\inf}
  robotSizeRadius: 10

  #Pixels per movement before transition adjustment, {1-\inf}
  robotNominalSpeed: 10

  #How far the targets icon extends in each direction, in pixels, {1-\inf}
  targetSizeRadius: 10

  #Number of steps in the comet trail, {0-\inf}
  breadCrumbLength: 100

  #Which pre-generated belief to use, {1-10}
  belNum: None